server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@//127.0.0.1:31521/XEPDB1
    username: saga_mgmt
    password: dudkrish1A
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: saga-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  main:
    banner-mode: off

app:
  kafka:
    topics:
      order: order-events
      payment: payment-events
      inventory: inventory-events
